config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :receipts

  root 'receipts#new'

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :receipt
  
  before_create :finalize_tax
  
  private
  
  def finalize_tax
    arr = ["chocolate", "pill", "book"]
    common_tax = arr.any? { |word| name.downcase.include?(word) } ? 0 : 10
    imported_tax = name.downcase.include?("imported")  ? 5 : 0
    total_tax = common_tax + imported_tax
    self.tax_perc =  total_tax
    calculate_tax
  end
  
  def calculate_tax
    amount = (tax_perc * price)/100
    
    a = ((amount * 100).round(0.2) ) * 0.1
    b = a/0.05
    if b != 0
      final_amount = (((b/10).ceil.to_f) * 5)/100
    else
      final_amount = a/100
    end
    self.tax_amount = final_amount
  end
end

app/models/receipt.rb
class Receipt < ActiveRecord::Base
  has_many :line_items
  accepts_nested_attributes_for :line_items, :reject_if => proc {|attributes| attributes.all? {|k,v| v.blank?} }
  
  after_create :calculate_tax
  
  def calculate_tax
    tax_amount = line_items.map(&:tax_amount).sum
    total = line_items.map(&:price).sum + tax_amount
    self.sales_tax = tax_amount
    self.total = total
    self.save!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController
  before_action :set_receipt, only: [:show, :edit, :update, :destroy]

  # GET /receipts
  # GET /receipts.json
  def index
    @receipts = Receipt.all
  end

  # GET /receipts/1
  # GET /receipts/1.json
  def show
  end

  # GET /receipts/new
  def new
    @receipt = Receipt.new
    4.times { @receipt.line_items.build }
  end

  # POST /receipts
  # POST /receipts.json
  def create
    @receipt = Receipt.new(receipt_params)

    respond_to do |format|
      if @receipt.save
        format.html { redirect_to @receipt, notice: 'Receipt was successfully created.' }
        format.json { render :show, status: :created, location: @receipt }
      else
        format.html { render :new }
        format.json { render json: @receipt.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_receipt
      @receipt = Receipt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def receipt_params
      params.require(:receipt).permit(:total, :sales_tax, :line_items_attributes => [:id, :name, :quantity, :price])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EllaRecords</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/receipts/_form.html.erb
<%= form_for(@receipt) do |f| %>
  <% if @receipt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@receipt.errors.count, "error") %> prohibited this receipt from being saved:</h2>

      <ul>
      <% @receipt.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.fields_for :line_items do |ff| %>
    <div class="field">
      <%= "Item #{ff.index + 1}" %>
    </div>
    <div class="field">
      <%= ff.text_field :name, placeholder: "Name" %>
      <%= ff.text_field :quantity, placeholder: "Quantity" %>
      <%= ff.text_field :price, placeholder: "Price" %>
    </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/receipts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Receipts</h1>

<table>
  <thead>
    <tr>
      <th>Total</th>
      <th>Sales tax</th>
      <th colspan="3"> Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @receipts.each do |receipt| %>
      <tr>
        <td><%= receipt.total %></td>
        <td><%= receipt.sales_tax %></td>
        <td><%= link_to 'Show', receipt %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Receipt', new_receipt_path %>

app/views/receipts/new.html.erb
<h1>New Receipt</h1>

<%= render 'form' %>

<%= link_to 'Back', receipts_path %>

app/views/receipts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="box-body">
  <table id="example2" class="table table-bordered table-striped table-responsive">
    <thead>
    <tr>
      <td>
        <b><%= t('name')%></b>
      </td>
      <td>
        <b><%= t('quantity')%></b>
      </td>
      <td>
        <b><%= t('price')%></b>
      </td>
    </tr>
    </thead>
    <tbody>
      <% @receipt.line_items.each do |item| %>
        <tr>
          <td><%= item.name %></td>
          <td><%= item.quantity %></td>
          <td><%= ((item.price + item.tax_amount) / 0.50).round(2) * 0.50 %></td>
        </tr>
      <%end%>
    </tbody>
  </table>
  <br />
</div>

<p>
  <strong>Total:</strong>
  <%= @receipt.total %>
</p>

<p>
  <strong>Sales tax:</strong>
  <%= @receipt.sales_tax %>
</p>

<%= link_to 'Back', receipts_path %>